import type { Category, Product, Testimonial, Order, Customer } from "./types"

export const categories: Category[] = [
  {
    id: "c1",
    slug: "silk-sarees",
    name: "Silk Sarees",
    description: "Lustrous pure silk weaves for timeless occasions.",
    image: "/products/silk-rose.png",
    productCount: 4,
  },
  {
    id: "c2",
    slug: "banarasi",
    name: "Banarasi",
    description: "Opulent brocade from the looms of Varanasi.",
    image: "/products/banarasi-gold.png",
    productCount: 3,
  },
  {
    id: "c3",
    slug: "kanjivaram",
    name: "Kanjivaram",
    description: "Regal South Indian silk with contrast zari borders.",
    image: "/products/kanjivaram-teal.png",
    productCount: 2,
  },
  {
    id: "c4",
    slug: "cotton-handloom",
    name: "Cotton Handloom",
    description: "Breathable everyday elegance, woven by hand.",
    image: "/products/cotton-maroon.png",
    productCount: 2,
  },
  {
    id: "c5",
    slug: "dupattas",
    name: "Dupattas & Stoles",
    description: "Finishing touches in silk and fine cotton.",
    image: "/products/dupatta-cream.png",
    productCount: 1,
  },
  {
    id: "c6",
    slug: "home-furnishings",
    name: "Home Furnishings",
    description: "Handwoven runners and textiles for the home.",
    image: "/products/home-runner.png",
    productCount: 1,
  },
]

export const products: Product[] = [
  {
    id: "p1",
    slug: "navy-kanjivaram-zari-saree",
    name: "Royal Navy Kanjivaram Silk Saree",
    category: "kanjivaram",
    categoryName: "Kanjivaram",
    price: 18999,
    compareAtPrice: 24999,
    rating: 4.9,
    reviewCount: 128,
    image: "/products/silk-navy.png",
    images: ["/products/silk-navy.png", "/products/banarasi-gold.png", "/products/kanjivaram-teal.png"],
    description:
      "A regal navy Kanjivaram woven on pure mulberry silk with a broad gold zari border. Each saree takes our master weavers nearly three weeks to complete on the traditional pit loom.",
    details: [
      "Pure mulberry silk with real zari",
      "Handwoven on a traditional pit loom",
      "Includes matching unstitched blouse piece",
      "Dry clean only",
    ],
    fabric: "Pure Mulberry Silk",
    color: "Navy Blue",
    colors: ["Navy Blue", "Maroon", "Emerald"],
    weave: "Kanjivaram",
    origin: "Kanchipuram, Tamil Nadu",
    stock: 8,
    sku: "PRH-KAN-001",
    badges: ["Best Seller", "Handwoven"],
    featured: true,
    bestSeller: true,
    newArrival: false,
  },
  {
    id: "p2",
    slug: "gold-ivory-banarasi-saree",
    name: "Gold & Ivory Banarasi Brocade Saree",
    category: "banarasi",
    categoryName: "Banarasi",
    price: 22499,
    compareAtPrice: 27999,
    rating: 5,
    reviewCount: 96,
    image: "/products/banarasi-gold.png",
    images: ["/products/banarasi-gold.png", "/products/silk-emerald.png", "/products/silk-navy.png"],
    description:
      "An heirloom Banarasi in ivory and gold, woven with intricate floral brocade. The perfect bridal companion, rich with the legacy of Varanasi looms.",
    details: [
      "Katan silk with intricate gold brocade",
      "Woven in Varanasi by award-winning artisans",
      "Heavy pallu with traditional kalga motifs",
      "Dry clean only",
    ],
    fabric: "Katan Silk",
    color: "Ivory Gold",
    colors: ["Ivory Gold", "Rose Pink", "Emerald"],
    weave: "Banarasi",
    origin: "Varanasi, Uttar Pradesh",
    stock: 5,
    sku: "PRH-BAN-002",
    badges: ["Best Seller", "Limited"],
    featured: true,
    bestSeller: true,
    newArrival: false,
  },
  {
    id: "p3",
    slug: "maroon-cotton-temple-saree",
    name: "Maroon Cotton Handloom Saree",
    category: "cotton-handloom",
    categoryName: "Cotton Handloom",
    price: 4299,
    rating: 4.7,
    reviewCount: 211,
    image: "/products/cotton-maroon.png",
    images: ["/products/cotton-maroon.png", "/products/fabric-indigo.png"],
    description:
      "A breathable handwoven cotton saree in deep maroon with a classic temple border. Effortless drape for everyday elegance and warm summer days.",
    details: [
      "100% handloom cotton",
      "Natural dyes, temple border",
      "Lightweight and breathable",
      "Machine wash gentle",
    ],
    fabric: "Handloom Cotton",
    color: "Maroon",
    colors: ["Maroon", "Indigo", "Mustard"],
    weave: "Cotton Handloom",
    origin: "Pochampally, Telangana",
    stock: 24,
    sku: "PRH-COT-003",
    badges: ["Handwoven"],
    featured: true,
    bestSeller: true,
    newArrival: false,
  },
  {
    id: "p4",
    slug: "teal-kanjivaram-contrast-saree",
    name: "Teal Kanjivaram Contrast Border Saree",
    category: "kanjivaram",
    categoryName: "Kanjivaram",
    price: 16499,
    compareAtPrice: 19999,
    rating: 4.8,
    reviewCount: 74,
    image: "/products/kanjivaram-teal.png",
    images: ["/products/kanjivaram-teal.png", "/products/silk-navy.png"],
    description:
      "A vivid teal Kanjivaram with a striking contrast red and gold border. A statement of South Indian grandeur for weddings and festivities.",
    details: [
      "Pure silk with contrast korvai border",
      "Handwoven in Kanchipuram",
      "Rich temple-inspired pallu",
      "Dry clean only",
    ],
    fabric: "Pure Silk",
    color: "Teal Green",
    colors: ["Teal Green", "Navy Blue"],
    weave: "Kanjivaram",
    origin: "Kanchipuram, Tamil Nadu",
    stock: 11,
    sku: "PRH-KAN-004",
    badges: ["Sale"],
    featured: true,
    bestSeller: false,
    newArrival: true,
  },
  {
    id: "p5",
    slug: "rose-silk-peacock-saree",
    name: "Rose Pink Silk Peacock Motif Saree",
    category: "silk-sarees",
    categoryName: "Silk Sarees",
    price: 13999,
    rating: 4.9,
    reviewCount: 152,
    image: "/products/silk-rose.png",
    images: ["/products/silk-rose.png", "/products/banarasi-gold.png"],
    description:
      "A romantic rose pink silk saree adorned with gold zari peacock motifs. Soft, luminous and made for celebrations.",
    details: [
      "Pure silk with zari peacock motifs",
      "Soft sheen, easy drape",
      "Matching blouse piece included",
      "Dry clean only",
    ],
    fabric: "Pure Silk",
    color: "Rose Pink",
    colors: ["Rose Pink", "Ivory Gold"],
    weave: "Silk",
    origin: "Kanchipuram, Tamil Nadu",
    stock: 14,
    sku: "PRH-SLK-005",
    badges: ["New", "Handwoven"],
    featured: true,
    bestSeller: true,
    newArrival: true,
  },
  {
    id: "p6",
    slug: "emerald-banarasi-floral-saree",
    name: "Emerald Banarasi Floral Saree",
    category: "banarasi",
    categoryName: "Banarasi",
    price: 19999,
    rating: 4.8,
    reviewCount: 63,
    image: "/products/silk-emerald.png",
    images: ["/products/silk-emerald.png", "/products/banarasi-gold.png"],
    description:
      "Deep emerald Katan silk woven with delicate gold florals. A jewel-toned Banarasi that commands every room.",
    details: [
      "Katan silk, gold brocade florals",
      "Woven in Varanasi",
      "Rich, heavy pallu",
      "Dry clean only",
    ],
    fabric: "Katan Silk",
    color: "Emerald",
    colors: ["Emerald", "Ivory Gold"],
    weave: "Banarasi",
    origin: "Varanasi, Uttar Pradesh",
    stock: 7,
    sku: "PRH-BAN-006",
    badges: ["New"],
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    id: "p7",
    slug: "cream-gold-silk-dupatta",
    name: "Cream & Gold Handwoven Silk Dupatta",
    category: "dupattas",
    categoryName: "Dupattas & Stoles",
    price: 3499,
    rating: 4.6,
    reviewCount: 89,
    image: "/products/dupatta-cream.png",
    images: ["/products/dupatta-cream.png"],
    description:
      "A versatile cream and gold silk dupatta with woven border and delicate tassels. The finishing flourish for any ensemble.",
    details: [
      "Pure silk with zari border",
      "Hand-knotted tassels",
      "Lightweight, generous length",
      "Dry clean recommended",
    ],
    fabric: "Pure Silk",
    color: "Cream Gold",
    colors: ["Cream Gold"],
    weave: "Silk",
    origin: "Chanderi, Madhya Pradesh",
    stock: 32,
    sku: "PRH-DUP-007",
    badges: ["New"],
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    id: "p8",
    slug: "indigo-ikat-cotton-fabric",
    name: "Indigo Ikat Handloom Fabric (per metre)",
    category: "cotton-handloom",
    categoryName: "Cotton Handloom",
    price: 899,
    rating: 4.5,
    reviewCount: 47,
    image: "/products/fabric-indigo.png",
    images: ["/products/fabric-indigo.png", "/products/cotton-maroon.png"],
    description:
      "Traditional indigo ikat cotton fabric sold by the metre. Hand-dyed and handwoven for kurtas, dresses and home projects.",
    details: [
      "100% handloom cotton",
      "Natural indigo dye",
      "Geometric ikat patterns",
      "Sold per running metre",
    ],
    fabric: "Handloom Cotton",
    color: "Indigo",
    colors: ["Indigo"],
    weave: "Ikat",
    origin: "Pochampally, Telangana",
    stock: 60,
    sku: "PRH-FAB-008",
    badges: ["Handwoven"],
    featured: false,
    bestSeller: false,
    newArrival: false,
  },
  {
    id: "p9",
    slug: "navy-gold-table-runner",
    name: "Navy & Gold Handloom Table Runner",
    category: "home-furnishings",
    categoryName: "Home Furnishings",
    price: 1799,
    rating: 4.7,
    reviewCount: 38,
    image: "/products/home-runner.png",
    images: ["/products/home-runner.png"],
    description:
      "A handwoven cotton table runner in navy and gold with tasselled ends. Brings handloom heritage to your dining table.",
    details: [
      "Handloom cotton blend",
      "Gold geometric border",
      "Tasselled finish",
      "Machine wash gentle",
    ],
    fabric: "Cotton Blend",
    color: "Navy Gold",
    colors: ["Navy Gold"],
    weave: "Handloom",
    origin: "Bhuj, Gujarat",
    stock: 45,
    sku: "PRH-HOM-009",
    badges: ["Best Seller"],
    featured: false,
    bestSeller: true,
    newArrival: false,
  },
  {
    id: "p10",
    slug: "ivory-silk-wedding-saree",
    name: "Ivory Silk Wedding Saree",
    category: "silk-sarees",
    categoryName: "Silk Sarees",
    price: 26999,
    compareAtPrice: 32999,
    rating: 5,
    reviewCount: 41,
    image: "/products/banarasi-gold.png",
    images: ["/products/banarasi-gold.png", "/products/silk-rose.png"],
    description:
      "An ivory and gold wedding saree woven for the most cherished day. Pure silk, real zari, and timeless grandeur.",
    details: [
      "Pure silk with real zari",
      "Bridal-weight pallu",
      "Matching blouse piece",
      "Dry clean only",
    ],
    fabric: "Pure Silk",
    color: "Ivory Gold",
    colors: ["Ivory Gold"],
    weave: "Silk",
    origin: "Kanchipuram, Tamil Nadu",
    stock: 4,
    sku: "PRH-SLK-010",
    badges: ["Limited", "Sale"],
    featured: true,
    bestSeller: false,
    newArrival: true,
  },
  {
    id: "p11",
    slug: "mustard-cotton-handloom-saree",
    name: "Mustard Cotton Handloom Saree",
    category: "silk-sarees",
    categoryName: "Silk Sarees",
    price: 5499,
    rating: 4.6,
    reviewCount: 58,
    image: "/products/cotton-maroon.png",
    images: ["/products/cotton-maroon.png"],
    description:
      "A sunny mustard handloom saree with contrast border. Lightweight, graceful and perfect for daytime gatherings.",
    details: [
      "Handloom cotton-silk blend",
      "Contrast woven border",
      "Soft, breathable drape",
      "Gentle wash",
    ],
    fabric: "Cotton Silk",
    color: "Mustard",
    colors: ["Mustard", "Maroon"],
    weave: "Handloom",
    origin: "Maheshwar, Madhya Pradesh",
    stock: 18,
    sku: "PRH-SLK-011",
    badges: ["New"],
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    id: "p12",
    slug: "deep-navy-silk-saree",
    name: "Deep Navy Pure Silk Saree",
    category: "silk-sarees",
    categoryName: "Silk Sarees",
    price: 15999,
    rating: 4.8,
    reviewCount: 110,
    image: "/products/silk-navy.png",
    images: ["/products/silk-navy.png", "/products/kanjivaram-teal.png"],
    description:
      "A deep navy pure silk saree with a fine gold border. Understated luxury that pairs with any occasion.",
    details: [
      "Pure silk, fine zari border",
      "Soft luminous finish",
      "Matching blouse piece",
      "Dry clean only",
    ],
    fabric: "Pure Silk",
    color: "Navy Blue",
    colors: ["Navy Blue", "Emerald"],
    weave: "Silk",
    origin: "Kanchipuram, Tamil Nadu",
    stock: 16,
    sku: "PRH-SLK-012",
    badges: ["Best Seller"],
    featured: false,
    bestSeller: true,
    newArrival: false,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Ananya Sharma",
    location: "Mumbai",
    rating: 5,
    quote:
      "The Banarasi I ordered for my wedding was breathtaking. The craftsmanship is unmatched and the gold work shimmers beautifully.",
  },
  {
    id: "t2",
    name: "Priya Nair",
    location: "Bengaluru",
    rating: 5,
    quote:
      "PR Handlooms feels like inheriting a piece of heritage. My Kanjivaram drapes like a dream and the colour is so rich.",
  },
  {
    id: "t3",
    name: "Meera Reddy",
    location: "Hyderabad",
    rating: 5,
    quote:
      "Beautiful handloom cottons that are perfect for everyday. Fast delivery and the packaging felt truly premium.",
  },
  {
    id: "t4",
    name: "Kavya Iyer",
    location: "Chennai",
    rating: 5,
    quote:
      "You can feel the artisan's love in every weave. I have bought four sarees now and each one is a treasure.",
  },
]

export const orders: Order[] = [
  { id: "#PRH-1042", customer: "Ananya Sharma", email: "ananya@example.com", date: "2026-06-18", total: 22499, status: "Processing", items: 1, paymentStatus: "Paid" },
  { id: "#PRH-1041", customer: "Priya Nair", email: "priya@example.com", date: "2026-06-17", total: 31298, status: "Shipped", items: 2, paymentStatus: "Paid" },
  { id: "#PRH-1040", customer: "Meera Reddy", email: "meera@example.com", date: "2026-06-17", total: 4299, status: "Delivered", items: 1, paymentStatus: "Paid" },
  { id: "#PRH-1039", customer: "Kavya Iyer", email: "kavya@example.com", date: "2026-06-16", total: 18999, status: "Delivered", items: 1, paymentStatus: "Paid" },
  { id: "#PRH-1038", customer: "Rohan Mehta", email: "rohan@example.com", date: "2026-06-15", total: 899, status: "Pending", items: 1, paymentStatus: "Pending" },
  { id: "#PRH-1037", customer: "Divya Pillai", email: "divya@example.com", date: "2026-06-14", total: 26999, status: "Cancelled", items: 1, paymentStatus: "Refunded" },
  { id: "#PRH-1036", customer: "Sneha Gupta", email: "sneha@example.com", date: "2026-06-13", total: 13999, status: "Delivered", items: 1, paymentStatus: "Paid" },
  { id: "#PRH-1035", customer: "Arjun Rao", email: "arjun@example.com", date: "2026-06-12", total: 5298, status: "Shipped", items: 3, paymentStatus: "Paid" },
]

export const customers: Customer[] = [
  { id: "u1", name: "Ananya Sharma", email: "ananya@example.com", phone: "+91 98200 11111", orders: 6, totalSpent: 98450, joined: "2024-02-12", status: "VIP" },
  { id: "u2", name: "Priya Nair", email: "priya@example.com", phone: "+91 98860 22222", orders: 4, totalSpent: 64200, joined: "2024-05-03", status: "VIP" },
  { id: "u3", name: "Meera Reddy", email: "meera@example.com", phone: "+91 99490 33333", orders: 2, totalSpent: 12800, joined: "2025-01-20", status: "Active" },
  { id: "u4", name: "Kavya Iyer", email: "kavya@example.com", phone: "+91 90030 44444", orders: 3, totalSpent: 47600, joined: "2025-03-11", status: "Active" },
  { id: "u5", name: "Rohan Mehta", email: "rohan@example.com", phone: "+91 99670 55555", orders: 1, totalSpent: 899, joined: "2026-06-10", status: "New" },
  { id: "u6", name: "Divya Pillai", email: "divya@example.com", phone: "+91 94440 66666", orders: 2, totalSpent: 39800, joined: "2025-08-22", status: "Active" },
]

export const revenueData = [
  { month: "Jan", revenue: 184000, orders: 42 },
  { month: "Feb", revenue: 221000, orders: 51 },
  { month: "Mar", revenue: 298000, orders: 68 },
  { month: "Apr", revenue: 256000, orders: 59 },
  { month: "May", revenue: 342000, orders: 81 },
  { month: "Jun", revenue: 410000, orders: 96 },
]

export const categorySales = [
  { name: "Banarasi", value: 38 },
  { name: "Kanjivaram", value: 27 },
  { name: "Silk Sarees", value: 19 },
  { name: "Cotton", value: 11 },
  { name: "Other", value: 5 },
]

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}

export function getProductById(id: string) {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(slug: string) {
  return products.filter((p) => p.category === slug)
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .concat(products.filter((p) => p.category !== product.category))
    .slice(0, limit)
}
